
#server.port=3032

#spring.application.name=config-client


#eureka.client.serviceUrl.defaultZone=http://localhost:7001/eureka/

server:
  port: 3032


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/